name: meta-watch
services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home

  database:
    image: mysql:8.0
    ports:
      - "3309:3306" 
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: db_password
    volumes:
      - database_data:/var/lib/mysql:rw
      - /var/run/docker.sock:/var/run/docker.sock

  backend: 
    tmpfs:
      - /var/www/html/var/cache
    build:
      context: ./Backend
      args:
        USER_ID: ${UID:-1001}
        GROUP_ID: ${GID:-1001}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes: 
      - ./Backend:/var/www/html
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontend
      args:
        USER_ID: ${UID:-1001}
        GROUP_ID: ${GID:-1001}
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    
volumes:

  database_data:
  
