name: meta-watch
services:
  database:
    image: mysql:8.0
    ports:
      - "3309:3306" 
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: "!ChangeMe!"
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: db_password
    volumes:
      - database_data:/var/lib/mysql:rw

  backend: 
    build: ./Backend
    volumes: 
      - ./Backend:/var/www/html
    ports:
      - "8000:8000"

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    
volumes:

  database_data:
