@startuml ListCreationDiagram
left to right direction
skinparam packageStyle rect

actor "User" as user
actor "Player" as player
actor "Admin" as admin

rectangle metawatch {
    (photos_user)
    (photos)
    (tournament)
    (listcreation)
    (faction)
    (unit)
    (detachment)
    (melee_weapon)
    (ranged_weapon)
    (stats)
    (morderate_user) as moderate
    (organise_tournament) as org_tournament

    ' Héritages pour la hiérarchie des droits
    admin --|> user
    player --|> user

    ' Fonctionnalités de base de l'User (héritées par Admin et Player)
    user -- (listcreation)
    user -- (photos_user)
    user -- (org_tournament)
    
    ' Fonctionnalités spécifiques
    player -- (tournament)
    admin -- (moderate)
    
    ' Relations internes
    (listcreation) ..> (faction) : <<include>>
    (photos_user) ..> (photos): <<include>>
    (faction) ..> (unit)
    (faction) ..> (detachment)
    (unit) ..> (melee_weapon) : <<include>>
    (unit) ..> (ranged_weapon) : <<include>>
    (unit) ..> (stats)
    (org_tournament) ..> (tournament) : <<include>>
}
@enduml