name: ci-metawatch

on:
  push:
    branches: 
      - 'features/**'


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix permissions
        run: sudo chown -R 1001:1001 .

      - name: Check Docker version
        run: docker --version
      
      - name: Log container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.META_WATCH_TOKEN }}

          
      
      - name: Run Deploy 
      
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          UID: 1001
          GID: 1001
        run:  DATABASE_URL="${DATABASE_URL}" make deploy

      - name: Debug files before deploy
        run: |
          ls -la Backend/
