name: ci-metawatch

on:
  push:
    branches: 
      - 'features/**'
  pull_request:
    branches:
      - 'main/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version
      
      - name: Log container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.META_WATCH_TOKEN }}

          
      
      - name: Run Deploy with Makefile
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: make deploy DATABASE_URL="${DATABASE_URL}"

      - name: Debug files before deploy
        run: |
          ls -la Backend/
